KitaitiMakoto/bibid

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build5975684010183945498">Bundle Update as a Service - Tachikoma.io</a>

Exec tachikoma update 20150223175452

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build5990904548941823600">Bundle Update as a Service - Tachikoma.io</a>

Exec tachikoma update 20150406175519

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6016270760595687989">Bundle Update as a Service - Tachikoma.io</a>

Exec tachikoma update 20150615175220

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6028954324981457943">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6028954324981457943">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20150720175229

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6031491043334010450">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6031491043334010450">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20150727175226

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6036564471471270508">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6036564471471270508">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20150810175227

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6039101194244493675">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6039101194244493675">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20150817175231

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6041637897057986410">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6041637897057986410">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20150824175234

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6046711310134162500">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6046711310134162500">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20150907175227

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6054321422957500135">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6054321422957500135">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20150928175229

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6059394911866402954">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6059394911866402954">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20151012175257

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6061931620924962531">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6061931620924962531">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20151019175215

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6064468337294272685">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6064468337294272685">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20151026175217

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6067005050635056385">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6067005050635056385">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20151102175220

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6077151914947348286">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6077151914947348286">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20151130175227

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6079688630940931829">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6079688630940931829">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20151207175230

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6082225347341127451">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6082225347341127451">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20151214175235

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6089835488520775905">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6089835488520775905">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20160104175230

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6102519062819282905">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6102519062819282905">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20160208175246

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6105055784144771833">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6105055784144771833">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20160215175250

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6107592506151726815">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6107592506151726815">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20160222175249

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6117739353514954815">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6117739353514954815">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20160321175321

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6122812783750387847">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6122812783750387847">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20160404175304

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6125349500190397640">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6125349500190397640">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20160411175257

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6130422930750035761">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6130422930750035761">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20160425175320

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6143106502992387313">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6143106502992387313">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20160530175320

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6145643219099296667">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6145643219099296667">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20160606175308

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6163400228205963812">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6163400228205963812">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20160725175219

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6165936944047203896">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6165936944047203896">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20160801175221

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6173547084100064087">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6173547084100064087">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20160822175224

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6188767383417896828">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6188767383417896828">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20161003175238

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6191304097790699580">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6191304097790699580">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20161010175231

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6193840809382076733">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6193840809382076733">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20161017175235

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6196377524438466315">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6196377524438466315">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20161024175232

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6198914241650134454">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6198914241650134454">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20161031175249

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6211597812637696839">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6211597812637696839">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20161205175251

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6214134529734509092">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6214134529734509092">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20161212175253

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6224281388261980046">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6224281388261980046">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20170109175214

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6257258687663124685">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6257258687663124685">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20170410175213

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6277552407315482011">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6277552407315482011">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20170605175213

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6280089116887589161">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6280089116887589161">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20170612175212

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6282625833269474624">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6282625833269474624">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20170619175212

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6285162552653940461">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6285162552653940461">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20170626175213

---

Gemfile.lock

Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6292772694061938686">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6292772694061938686">2015-06-28 Updated permissions - Tachikoma.io</a>

Exec tachikoma update 20170717175213
